# Generated by Django 2.1.5 on 2019-01-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_detail',
            name='adhar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
