# Generated by Django 2.1.5 on 2019-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190112_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
